//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by REPLAY.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_CHANDIALOG                  101
#define IDC_CHAN1                       102
#define IDC_CHAN2                       103
#define IDC_CHAN3                       104
#define IDC_CHAN4                       105
#define IDC_CHAN5                       106
#define IDC_CHAN6                       107
#define IDC_CHAN7                       108
#define IDC_CHAN8                       109
#define IDC_COLOUR1                     110
#define IDC_COLOUR2                     111
#define IDC_COLOUR3                     112
#define IDC_COLOUR4                     113
#define IDC_COLOUR5                     114
#define IDC_COLOUR6                     115
#define IDC_COLOUR7                     116
#define IDC_COLOUR8                     117
#define IDC_DECPL1                      118
#define IDC_DECPL2                      119
#define IDC_DECPL3                      120
#define IDC_DECPL4                      121
#define IDC_DECPL5                      122
#define IDC_DECPL6                      123
#define IDC_DECPL7                      124
#define IDC_DECPL8                      125
#define IDC_CHANNAME                    126
#define IDC_COLOUR                      127
#define IDC_PLACES                      128
#define IDC_READING                     129
#define IDD_READDIALOG                  130
#define IDC_READCHAN                    131
#define IDD_COLOUR_DIALOG               132
#define IDC_CLEAR_ALL                   133
#define IDC_DEFAULTS                    134
#define IDC_COLOUR_RED                  135
#define IDC_COLOUR_GREEN                136
#define IDC_COLOUR_BLUE                 137
#define IDC_COLOUR_CYAN                 138
#define IDC_COLOUR_MAGENTA              139
#define IDC_COLOUR_YELLOW               140
#define IDC_LINE_COLOUR                 141
#define IDC_VERSION                     142
#define IDC_COPYRIGHT                   143
#define IDC_SERIALNO                    144
#define ID_ZOOM_OUT                     32768
#define ID_ZOOM_OUT_X                   32770
#define ID_ZOOM_OUT_Y                   32771
#define ID_ZOOM_OUT_BOTH                32772
#define ID_REPLAY_GOTOSTART             32773
#define ID_REPLAY_GOTOEND               32774
#define ID_REPLAY_FORWARD               32775
#define ID_REPLAY_REVERSE               32776
#define ID_REPLAY_FASTFORWARD           32777
#define ID_REPLAY_FASTREVERSE           32778
#define ID_REPLAY_STOP                  32779
#define ID_CHANNELS                     32780
#define ID_HELP_CONTENTS                32781
#define ID_HELP_HOWTOUSEHELP            32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
